### PR TITLE
mrc-1426 contains MINT prevalence and cases averted graphs

### PR DESCRIPTION
**Pull request by hillalex**

### CODE REVIEW

**Review by EmmaLRussell — COMMENTED** [review]
Looks great! Are those little error bars on the shiny app bar chart? Should we include those?

Is the reason that you've gone for plotly rather than chartjs because plotly's more aligned with ggplot?

**Comment by hillalex** [comment]
> Looks great! Are those little error bars on the shiny app bar chart? Should we include those?
> 
> Is the reason that you've gone for plotly rather than chartjs because plotly's more aligned with ggplot?

Missed those, cool will add :+1: Partly went for Plotly because I was thinking about HtmlWidgets, partly because it was mentioned to me during data-viz user sessions and generally just seems whizzier and better than chartjs. I guess less important here because the plot have so few data points, but in the dataviz tool being able to zoom in on parts of the graph is important for readability.

**Comment by hillalex** [comment]
Why did we choose chartjs over plotly in the past?

**Comment by EmmaLRussell** [comment]
> Why did we choose chartjs over plotly in the past?

Can't remember, I think maybe we thought it looked slightly nicer but I don't think there was much in it.

**Review by EmmaLRussell — APPROVED** [review]

**Pull request merged**
